version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - "4506:3306"
    restart: always
    environment:
      - MYSQL_DATABASE=hippy_app_db
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./tmp/db:/var/lib/mysql
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/hippy_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db